executor: slurm
jobs: 20
latency-wait: 300
rerun-incomplete: true
keep-going: true
retries: 3

default-resources:
    slurm_extra: "--nodelist=mjolnircomp15fl --reservation=course_1 --account=teaching"
    mem_mb: 8 * 1024
    runtime: 10 * 2 ** (attempt - 1)
max-threads: 8
